version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: projetomodelodb
  phpmyadmin:
    image: phpmyadmin:5
    container_name: phpmyadmin
    ports:
      - 8081:80
    restart: "no"
    environment:
      PMA_HOST: db
    depends_on:
      - db
volumes:
  mysql-volume:
